projects:
  VolticRootStackAPI-test:
    schemaPath: graphql/schema.json
    includes:
      - graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        graphQLApiId: ndb5oyhatbailavp2hkreqsuhq
        codeGenTarget: swift
        generatedFileName: API.swift
        docsFilePath: graphql
        region: us-east-1
        maxDepth: 6
      endpoints:
        prod: >-
          https://nvjgohm4hvdbphexj7alurtnpu.appsync-api.us-east-1.amazonaws.com/graphql
