projects:
  ServinChatGraphQL:
    schemaPath: graphql/schema.json
    includes:
      - graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        graphQLApiId: dbx5yvxssjdrxhaxd7xagyzvzq
        codeGenTarget: swift
        generatedFileName: ChatAPI.swift
        docsFilePath: graphql
        region: us-east-1
      endpoints:
        prod: >-
          https://pn2eszmr25f3bgg4hdypm7gijy.appsync-api.us-east-1.amazonaws.com/graphql
