projects:
  AppSynctestEnvAPI-test:
    schemaPath: graphql/schema.json
    includes:
      - graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        graphQLApiId: 5pwarryqerg4dac26kjnlfxv6q
        codeGenTarget: swift
        generatedFileName: API.swift
        docsFilePath: graphql
        region: us-east-1
        maxDepth: 6
      endpoints:
        prod: >-
          https://s5qtmtbepjhm3fg4gn3rux4lyu.appsync-api.us-east-1.amazonaws.com/graphql
