# /* Copyright (C) Voltic Labs, Inc - All Rights Reserved
#  * Unauthorized copying of this file, via any medium is strictly prohibited
#  * Proprietary and confidential
#  */

AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: CloudFormationStack by Voltic Labs Inc. Copyright (C) Voltic Labs, Inc - All Rights Reserved. Unauthorized copying of this file, via any medium is strictly prohibited. Proprietary and confidential.

Parameters:
  APIName:
    Type: String
    Description: "Name of the API, to generate names for resources"
    MinLength: 3
    MaxLength: 20
    Default: VolticRootStackAPI
    AllowedPattern: '^[a-zA-Z][a-zA-Z0-9_]*$'

  ReleaseEnvironment:                                                        # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/conditions-sample-templates.html
    Description: Environment type.
    Default: dev
    Type: String
    AllowedValues: [prod, dev, test]
    ConstraintDescription: must specify prod, dev, or test.

  AuthName:
    Type: String
    Default: VolticRootStackAuth
    Description: Unique Auth Name for the AWS Cognito Resources (User Pool, Identity Pool, IAM roles, etc...)
    MinLength: 3
    MaxLength: 20
    AllowedPattern: '^[a-zA-Z][a-zA-Z0-9_]*$'

  StorageName:
    Type: String
    Default: VolticRootStackStorage
    Description: Unique Storage Name for the AWS Cognito Resources (User Pool, Identity Pool, IAM roles, etc...)
    MinLength: 3
    MaxLength: 30
    AllowedPattern: '^[a-zA-Z][a-zA-Z0-9_]*$'

  UserPoolGivenNameMaxLength: 
    Type: Number
    Default: 32
    Description: Maximum length of the given-name attribute in the User Pool.
  UserPoolGivenNameMinLength: 
    Type: Number
    Default: 1
    Description: Minmum length of the given-name attribute in the User Pool.

  UserPoolFamilyNameMaxLength: 
    Type: Number
    Default: 32
    Description: Maximum length of the family-name attribute in the User Pool.
  UserPoolFamilyNameMinLength: 
    Type: Number
    Default: 1
    Description: Minimum length of the family-name attribute in the User Pool.

  StripeSecretKey:
    Type: String
    Description: Secret key used for making calls to the Stripe API.
    Default: sk_test_a5oPV0ep4DACJfPSCtsKQPZr

  StripeEndpointSecret:
    Description: Secret value of the endpoint, this value is generated by stripe
    Type: String
    Default: whsec_pqEHDgPIyBYlnLpY9PIsOka4OLyAQRDi

  DynamoDBStripeTableName:
    Description: Name of the dynamodb table that holds stripe usernames corelating to each account/customer id
    Type: String

  DynamoDBUserTableName:
    Description: Name of the dynamodb table that holds user information such as sign up date, first/last name, school, categories and so on.
    Type: String

#########################################################################################################################################################
Outputs:

  GraphQLApiId:
    Description: Unique AWS AppSync GraphQL API Identifier
    Value: !GetAtt APIStack.Outputs.ChatQLApiId
  GraphQLApiUrl:
    Description: The Endpoint URL of your GraphQL API.
    Value: !GetAtt APIStack.Outputs.ChatQLApiUrl

  UserPoolID:
    Description: Unique ID of the Cognito UserPool
    Value: !GetAtt UserPoolStack.Outputs.UserPoolID
  UserPoolARN:
    Description: Unique ARN of the Cognito UserPool
    Value: !GetAtt UserPoolStack.Outputs.UserPoolARN
  IdentityPoolID:
    Description: Unique ID of the Cognito Identity Pool
    Value: !GetAtt UserPoolStack.Outputs.IdentityPoolId
  UserPoolClientID:
    Description: Unique ID of the iOS App client for the User Pool
    Value: !GetAtt UserPoolStack.Outputs.iOSAppClientID
  UserPoolClientSecret:                                               # This isn't supported right now, workaround: https://forums.aws.amazon.com/thread.jspa?messageID=800824&tstart=0
    Description: Secret of the iOSAppClient
    Value: !GetAtt UserPoolStack.Outputs.iOSAppClientSecret

  S3BucketName:
    Description: Resource name of the s3 bucket
    Value: !GetAtt S3Stack.Outputs.S3BucketName

  PinpointAppId:
    Description: App id of the pinpoint application
    Value: !GetAtt PinpointStack.Outputs.PinpointAppId

  PinpointAppRegion:
    Description: Region of the pinpoint application
    Value: !GetAtt PinpointStack.Outputs.PinpointAppRegion

Resources:

  APIStack:
    Type: "AWS::Serverless::Application"                                        # 0A https://github.com/awslabs/serverless-application-model/releases/tag/v1.9.0
    Properties:
      # NotificationARNs:                                                       # 1A
      #   - String
      Parameters:                                                               # 1B
        APIName:                 !Sub ${APIName}
        ReleaseEnvironment:      !Sub ${ReleaseEnvironment}
        UserPoolId:              !GetAtt UserPoolStack.Outputs.UserPoolID
        PinpointAppId:           !GetAtt PinpointStack.Outputs.PinpointAppId
        UserDynamoDBTableName:   !GetAtt UserDynamoDBTableStack.Outputs.TableName
        UserDynamoDBTableArn:    !GetAtt UserDynamoDBTableStack.Outputs.Arn
        # DynamoDBStripeTableName: !GetAtt StripeStack.Outputs.DynamoDBStripeTableName
      # Tags:
      #   - Tag
      Location: "./AppSync/template.yaml"
      # TimeoutInMinutes: Integer                                                # 1C
  

  UserPoolStack:
    Type: "AWS::Serverless::Application"
    Properties:
      # NotificationARNs:
      #   - String
      Parameters:
        AuthName: !Sub ${AuthName}
        ReleaseEnvironment: !Sub ${ReleaseEnvironment}
        UserPoolGivenNameMaxLength: !Sub ${UserPoolGivenNameMaxLength}
        UserPoolGivenNameMinLength: !Sub ${UserPoolGivenNameMinLength}
        UserPoolFamilyNameMaxLength: !Sub ${UserPoolFamilyNameMaxLength}
        UserPoolFamilyNameMinLength: !Sub ${UserPoolFamilyNameMinLength}
        StripeLambdaLayer: !GetAtt LambdaLayers.Outputs.StripeLambdaLayer
        StripeSecretKey: !Sub ${StripeSecretKey}
        UserDynamoDBTableName: !GetAtt UserDynamoDBTableStack.Outputs.TableName
        DynamoDBStripeTableName: !Sub ${DynamoDBStripeTableName}
        # UtilitiesLayer:       !GetAtt LambdaLayers.Outputs.UtilitiesLambdaLayer
      # Tags:
      #   - Tag
      Location: "./Auth/template.yaml"
      # TimeoutInMinutes: Integer
  
  S3Stack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      # NotificationARNs:
      #   - String
      Parameters:
        StorageName: !Sub ${StorageName}
        ReleaseEnvironment: !Sub ${ReleaseEnvironment}
        AuthRole: !GetAtt UserPoolStack.Outputs.AuthRole
        UserDynamoDBTableName: !GetAtt UserDynamoDBTableStack.Outputs.TableName
      # Tags:
      #   - Tag
      TemplateURL: "./S3/template.yaml"
      # TimeoutInMinutes: Integer
  
  PinpointStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      # NotificationARNs:
      #   - String
      Parameters:
        ReleaseEnvironment: !Sub ${ReleaseEnvironment}
        AppName: Servin
        iOSBundleId: com.volticlabs.servin
        iOSTeamId: CFQRSECJY5
        TokenKey: |
                    MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgtCKL4dDMLYxu3L3d
                    bbgibobmANulmxuYilNNHYns8cigCgYIKoZIzj0DAQehRANCAASitoAI0rCBdaiw
                    lNvs9AvBveI3tPoh5KBZS6B4OZF2mBUbt7+0erYIvKybWkYRC0bb1befIwc+lZHd
                    S4R5okEf
        TokenKeyId: Z2Q2R4L423
        AuthRole: !GetAtt UserPoolStack.Outputs.AuthRole
      # Tags:
      #   - Tag
      TemplateURL: "./Pinpoint/template.yaml" #required
      TimeoutInMinutes: 15

  LambdaLayers:
    Type: AWS::Serverless::Application
    Properties:
      Location: "./Lambda-Layers/template.yaml"
      # Parameters:
      #   StringParameter: parameter-value
      #   IntegerParameter: 2
      # Tags:
      #   - Key: LambdaLayersStackKey
      #     Value: LambdaLayersStackValue
      TimeoutInMinutes: 15

  StripeStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      # NotificationARNs:
      #   - String
      Parameters:
      #   CustomResourceLayer:  !GetAtt LambdaLayers.Outputs.CustomResourceLambdaLayer
      #   UtilitiesLayer:       !GetAtt LambdaLayers.Outputs.UtilitiesLambdaLayer
        StripeLambdaLayer:      !GetAtt LambdaLayers.Outputs.StripeLambdaLayer
        StripeSecretKey:        !Sub ${StripeSecretKey}
        StripeEndpointSecret:   !Sub ${StripeEndpointSecret}
        GraphQLApiId:           !GetAtt APIStack.Outputs.ChatQLApiId
        DynamoDBStripeTableName: !Sub ${DynamoDBStripeTableName}
      # Tags:
      #   - Key: CognitoStackKey
      #     Value: CognitoStackValue
      TemplateURL: "./Stripe/template.yaml"
      TimeoutInMinutes: 15

  UserDynamoDBTableStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      Parameters:
        TableName: !Sub ${DynamoDBUserTableName}
      # Tags:
      #   - Tag
      TemplateURL: "./DynamoDB/usersTable.yaml"
      TimeoutInMinutes: 15
